# Generated by Django 4.2.6 on 2023-11-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_No', models.IntegerField()),
                ('Departure_Time', models.DateTimeField()),
                ('Destinations', models.CharField(max_length=500)),
                ('Seats_Available', models.IntegerField()),
                ('TicketsCosts', models.CharField(max_length=100)),
            ],
        ),
    ]
