# Generated by Django 4.2.6 on 2023-11-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Busapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='Bus_No',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='Departure_Time',
            field=models.TimeField(),
        ),
    ]
